# Generated by Django 3.2 on 2021-05-05 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0, null=True)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_time', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
